### ISSUE TITLE
Removed student cannot log back in

### ISSUE THREAD

**Issue by mssiegel** [mssiegel/frempco-client#111]
There is a bug preventing kicked out students from signing back in.

Steps to reproduce:
1) Teacher kicks a student out of the classroom
2) The removed student returns to the homepage by either clicking their browser's back button or the hompage link
3) The removed students signs back in on the homepage.  The student's screen says: "Your teacher will pair you soon". But their name does NOT appear on teachers page.

**Comment by zachlankton** [comment]
This bug was introduced back in february in PR https://github.com/mssiegel/frempco-server/pull/9

The code to add a new student was refactored to push a student's socket id into the classroom instead of a student object, but the code to remove a student from a classroom was NOT refactored to use the socket id instead of an object.  Because of this, the student is still "in the classroom" on the server side.

![Capture](https://user-images.githubusercontent.com/2927894/161450797-ee9fb3b4-0199-4967-b185-c652252c6cd9.PNG)

The code that was added in PR https://github.com/mssiegel/frempco-server/pull/13 checks if a student is already in the classroom.  If a student with the same socket id tries to enter, this check will prevent that from happening.

This bug was masked because student needed to hit the back button or refresh to rejoin, which would generate a new socket id.  Now that we have a link for the student to go back to the homepage, the socket id remains the same.

The fix for this problem is to refactor the remove student code to remove the student using their socket id as shown below:

![Capture2](https://user-images.githubusercontent.com/2927894/161451220-7c67d275-1582-484b-8ed5-e335f2aef73c.PNG)
