### ISSUE TITLE
Ability for teacher to send message in chats

### ISSUE THREAD

**Issue by karlrez** [mssiegel/frempco-client#74]
I think the teacher should be able to jump into a chat and send a message.

Would add an input to the chat like so (would style it to match the student chatbox):
![image](https://user-images.githubusercontent.com/47090434/157173131-df5abfcf-f382-4000-b8f0-0ab971c04a4e.png)

**Comment by mssiegel** [comment]
This could be a great idea, but its too premature. Ariella is the only teacher who used Frempco so far, and when she did I think she was standing the whole time. The teachers we're reaching out to teach in a physical space. So they'll tend to walk around the classroom from student to student.  
They're often standing up when they use the mouse to click through the students displayed chats. Instead of sitting down to type, its usually faster for them to walk to the students desk and speak to them directly.

I feel this would be phenomenal when we start having teachers who use Frempco with their students **remotely**. 

To keep the Github issue list clean, @karlrez I feel this issue should be closed. We can reopen or recreate this issue when a teacher asks for this!

**Comment by karlrez** [comment]
That makes sense! Will close for now
