### ISSUE TITLE
Ability for student to unpair

### ISSUE THREAD

**Issue by karlrez** [mssiegel/frempco-client#75]
If student wants to leave the conversation

**Comment by mssiegel** [comment]
We need to speak to teachers first and see what they think of an "end chat" button. Because I worry students might purposely unmatch if they get paired with a boring student. And then the boring student will find himself getting unmatched over and over.  
We should get teacher input on this. I just created a "needs teacher input" label and put it on this issue.

**Comment by karlrez** [comment]
Good point there! Definitely don't want to add a feature that can lead to unwanted behaviour.
