### ISSUE TITLE
Dev link shortcut not adding student to classroom

### ISSUE THREAD

**Issue by karlrez** [mssiegel/frempco-client#79]
It seems that this shortcut link for students:
![image](https://user-images.githubusercontent.com/47090434/157367294-f80fca08-25db-4a3f-9b8c-0b9a060fcb3e.png)
is not adding the student to any classroom. I think when using this link the student can be directed to the test classroom or get the alert "test classroom not set up"

**Comment by zachlankton** [comment]
Good Catch @karlrez .  Personally I do not use these dev links. 

In order to make the `Visit Students classroom page` link work correctly it will need to basically run much of the same code for the `Students Page` button but with some hardcoded (maybe random name) values.  While technically possible (just need to refactor `visitStudentsPage` linked below so that it will work with both the modal and hardcoded parameters passed in), I wonder if this is really worth bothering with and if the dev links could be removed?

Will need @mssiegel to sign off on this but those are my thoughts.

https://github.com/mssiegel/frempco-client/blob/4b486208503e529e2003107cca3365f532db5e6e/pages/index.tsx#L65

**Comment by mssiegel** [comment]
Oh I use the teacher dev link all the time!!! I use it when I pull down Zach's PRs and quickly login as teacher. If this student dev link is fixed, I'd use it too!!!
I think we should create a `testVisitStudentsPage()` function that runs when this button is clicked. It would assign hardcoded random student values.  Maybe like `"student <random value 1-10000>"`.   This test function will skip the need for opening up the modal.  I'd love the ability to login as a test student with just one click!!!!

Karl I'm assigning this task to you.
